version: '3.9'

services:
  web:
    build: .
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A setup worker --loglevel=info --pool=solo
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A setup beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
    env_file:
      - .env