# Generated by Django 5.2 on 2025-04-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('staff', 'Staff'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
