# Generated by Django 5.2 on 2025-04-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_quarto_reserva_delete_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='preco_por_noite',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='tipo',
        ),
    ]
