# Generated by Django 5.2 on 2025-04-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_quarto_preco_por_noite_remove_quarto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='endereco',
        ),
    ]
