# Generated by Django 5.2 on 2025-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_reserva_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='numero_quartos',
            field=models.IntegerField(null=True),
        ),
    ]
